### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by xiaoyufenfei** [Tramac/Lightweight-Segmentation#1]
@Tramac 
hope that the dataset part of this link will help you load some new datasets.
https://github.com/xiaoyufenfei/EDDSNet/tree/master

**Comment by Tramac** [comment]
Hi, thank you for your great job, It is helpful!

**Comment by xiaoyufenfei** [comment]
@Tramac 
and here is repo for some segmodel ,hope will help you project organization.
https://github.com/xiaoyufenfei/Real-Time-Semantic-Segmentation/tree/master/Real-Time%20SegModel

**Comment by Tramac** [comment]
Great!
