### ISSUE TITLE
could this eval by CPU?

### ISSUE THREAD

**Issue by sybil12** [Tramac/Lightweight-Segmentation#13]
rt, I want to eval at a CPU machine, how to do it?

**Comment by Tramac** [comment]
Please change [this](https://github.com/Tramac/Lightweight-Segmentation/blob/71bf91f3d5b946a046becfd5d8667e8a0f80d630/light/model/mobilenet_seg.py#L46) to `model.load_state_dict(torch.load(get_model_file('mobilenet_%s_best_model' % (acronyms[dataset]), root=root)), map_location='cpu')` if you want to use mobilenet.
