### ISSUE TITLE
Instance sematic segmentation 

### ISSUE THREAD

**Issue by abhigoku10** [Tramac/Lightweight-Segmentation#8]
@Tramac  thanks for the wonderful code base , i have few following queries 

1. Can we use the architectures like efficient net , shuffle net for instance segmentation 
2. How much work around will it be there if we have to use the following for instance segmentation

**Comment by Tramac** [comment]
Hi, thank you for your attention. Here is my personal opinion：
1. There is no detection part for instance segmentation, but it is possible to use the architecture(efficient, mobilenet) as a backbone network to achieve feature extraction.
2. The main work is to add detection branch for instance segmentation.
