### ISSUE TITLE
TypeError: object of type 'COCOSegmentation' has no len()

### ISSUE THREAD

**Issue by pandamax** [Tramac/Lightweight-Segmentation#9]
I have added mscoco.py from [the project](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/tree/master/core/data/dataloaderl) that you did suggest.

I guess the problem below arises because of the incompatibility between python's version and pycocotools. Is there any suggestion to modify  the code? thanks in advance.

train set
loading annotations into memory...
Done (t=0.89s)
creating index...
index created!
Traceback (most recent call last):
  File "train.py", line 291, in <module>
    trainer = Trainer(args)
  File "train.py", line 106, in __init__
    args.iters_per_epoch = len(trainset) // (args.num_gpus * args.batch_size)
TypeError: object of type 'COCOSegmentation' has no len()

**Comment by Tramac** [comment]
Please add function `def __len__(self)` in `mscoco.py`.
